version = 0.1

[default.deploy.parameters]
stack_name = "incidentSystem"
resolve_s3 = true
s3_prefix = "incidentSystem"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = [
  "JwtSecret=KFCPACKAGE499",
  "LineChannelAccessToken=Z2QLS2+EWWCVKzMIvRwnHLzMpue6rbTiVQ87PSrvKYggU/ca052XPbyN94S7Roks9EMUhOhc6Fz0wJXuv+8L3Re3rajyFntWbFj3KiIDygtT9TkFlwwHOKmf3m0/oQOdy17Gg43gOupEpadp+XxfJwdB04t89/1O/w1cDnyilFU=",
  "LiffUrl=https://liff.line.me/2009444975-WqhF6Iws",
  "AgencyWebLiffUrl=https://liff.line.me/2009444975-NsMS2WyX",
  "LineChannelId=2009444975",
]

[default.global.parameters]
region = "us-east-1"
